import '@/styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import { useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link';

import AOS from "aos";

import "aos/dist/aos.css";

export default function App({ Component, pageProps }) {
  useEffect(() => {
    
    import("bootstrap/dist/js/bootstrap");
  }, []);
  useEffect(() => {
    AOS.init({
      easing: "ease-out-cubic",
      once: true,
      offset: 50,
    });
  }, []);
 
  return (
    <>
      <Head>
        <title>bootstrap®</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <title>Bootstrap demo</title>
          <Link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"/><Link rel="icon" href="/favicon.ico" />
            <Link rel="preconnect" href="https://fonts.googleapis.com" />
            <Link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <Link href="https://fonts.googleapis.com/css2?family=Mouse+Memoirs&display=swap" rel="stylesheet"></Link>
            <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
          </Head>

          <Component {...pageProps} />
        </>

        )
}



