import styles from '@/styles/Home.module.css'
import Link from "next/link";
import Head  from "next/head";
export default function Register() {
    async function Register(e){
        e.preventDefault();
        const [username,password,first_name,last_name] = e.target.elements;
        var formdata = new FormData;
        formdata.append("email",username.value);
        formdata.append("pass",password.value);
        formdata.append("first_name",first_name.value);
        formdata.append("last_name",last_name.value);
        const config = {
  headers: { "content-type": "multipart/form-data" },
};
        await axios.post("http://localhost:8080/TestHtml/register.php",formdata,config).then((response) => {
            if (response.data == "success"){
                alert("register success you can login now");
                window.location.assign("/TestHtml/")
            }else{
                alert ("fail")        
            }
});
}
    return (
        <>
        <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.3/axios.min.js" integrity="sha512-L4lHq2JI/GoKsERT8KYa72iCwfSrKYWEyaBxzJeeITM9Lub5vlTj8tufqYk056exhjo2QDEipJrg6zen/DDtoQ==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <header className="top-header">
            <a className="menu-item brand" style={{alignItems: 'baseline'}} href="">หน้าแรก</a>
            <a className="menu-item" style={{alignItems: 'baseline'}} href="">แนะนำ</a>
            <a className="menu-item" href="Food.html">ของกิน</a>
            <a className="menu-item" style= {{alignItems: 'flex-end'}} href="">Login</a>
        </header>
      </Head>
      <main>
      <form onSubmit= "Register(event)" >
        <div classname="container">
            <div classname="bg">
                <h1>Register</h1>
            <div classname="email">
                <input type="email" name="username" placeholder="email" required/>
            </div>
            <div classname="password">
            <input type="password" name="password" placeholder="password" required/>
        </div>
            <div classname="first name">
            <input type="text" name ="first_name" placeholder="first name" required/>
        </div>
            <div classname="last name">
            <input type="text" name="last_name" placeholder="last name" required/>
        </div>
            <input type="submit" value="Register"/>
        </div>
        </div>
        
        </form>
        </main>
        </>
        
      )
  }
  