import styles from '@/styles/Home.module.css'
import Link from "next/link";
import Head  from "next/head";
export default function Register() {
    async function forgot(e){
        e.preventDefault();
        const [email] = e.target.elements;
        var formdata = new FormData;
        formdata.append("email",email.value);
        const config = {
  headers: { "content-type": "multipart/form-data" },
};
        await axios.post("https://www.imgen.site/imgen2/api_male/forget.php?fbclid=IwAR3UzWowv_zcd3nATI9YI_aW8gB5FgBWUtey3HZnD6KvWyn-jyQdjx3UTds",formdata,config).then((response) => {
            var datax = response.data ;
            if (datax.status == "success"){
                alert("we send to you email"+datax.first_name);
            } else if (datax == "no"){
                alert("no this email member")
            }else{
                alert ("we not send to you email") 
                console.log(datax)       
            }
});
}
    return (
        <>
        <Head>
        <title>forget</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.3/axios.min.js" integrity="sha512-L4lHq2JI/GoKsERT8KYa72iCwfSrKYWEyaBxzJeeITM9Lub5vlTj8tufqYk056exhjo2QDEipJrg6zen/DDtoQ==" 
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <header className="top-header">
            <a className="menu-item brand" style={{alignItems: 'baseline'}} href="">หน้าแรก</a>
            <a className="menu-item" style={{alignItems: 'baseline'}} href="">แนะนำ</a>
            <a className="menu-item" href="Food.html">ของกิน</a>
            <a className="menu-item" style= {{alignItems: 'flex-end'}} href="">Login</a>
        </header>
      </Head>
      <main>
      <form onSubmit= "forgot(event)" >
		<div classname="container">
            <h1>Forget Password</h1>
            <div><input type="email" name="email" placeholder="email" required/></div>
            <div classname="submit">
                <input type="submit" value="forgot"/>
            </div>
        </div>
	</form>
        </main>
        </>
        
      )
  }