import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import me from '../pages/img/me.png'

const inter = Inter({ subsets: ['latin'] })

export default function resume() {
  return (
    <>
      <Head>
        <title>Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className=' bg-body-secondary'>
        {/*  */}
        <nav class="navbar bg-body-tertiary  d-lg-none  fixed-top ">
          <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
              data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon">
              </span>
            </button>
            <sidebar class="offcanvas offcanvas-start   " tabindex="-1" id="offcanvasNavbar"
              aria-labelledby="offcanvasNavbarLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">My Resume</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                      aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li>
                        <hr class="dropdown-divider" />
                      </li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex mt-3" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </sidebar>
          </div>
        </nav>
        
        <sidebar class="d-flex flex-column lh-base bg-white flex-shrink-0 p-3 m-3 "style={{ width: '280px'}} >
          <div class="d-flex align-self-center px-5 mt-3  me-0  link-body-emphasis text-decoration-none">
          <Image src={me} class="card-img align-self-center  image-fluid bb"  height={150} alt="..." />
          </div>
          <div class="d-flex text-center align-self-center   mt-3  me-0   link-body-emphasis text-decoration-none">
          <p class="fs-4 d-flex  ff">Sidebar</p>
          </div>
          
          <hr></hr>
        </sidebar>
      </body>
    </>
  )
}
