import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import imghead from '../pages/img/Bootstrap_logo.png'
import Link from 'next/link'
import Header from './head.js'
import s1 from '../pages/img/s1.png'
import s2 from '../pages/img/s2.png'
import s3 from '../pages/img/s3.png'
import s4 from '../pages/img/s4.png'
export default function Home() {
  return (
    <>
      <Head>
        <title>bootstrap®</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className=''>
        <div className='bg ff'>
          <div className='container position-relative overflow-hidden prr  text-center'>
            <div className="container font-monospace py-5 lh-base mx-auto my-5 text-white">
              <p className="fs-1 fw-bold ">BOOTSTRAP® </p>
              <p className="fs-6 fw-bold ">  Build fast, responsive sites with Bootstrap</p>
              <p className="lead1">
                <a href="https://www.callofduty.com/warzone" class="btn btn-primary fs-6 fw-bold ff">READ MORE</a>
              </p>
            </div>
          </div>
        </div>
        <div className='bg2'>
          <div className='container position-relative overflow-hidden prr  text-center'>
            <div className="container font-monospace py-5 lh-base mx-auto my-5 text-white">
              <p className="fs-1 fw-bold ">Build fast, responsive sites with Bootstrap </p>
              <p className="fs-6 fw-bold ">Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins.</p>
              <p className="lead1">
                <a href="https://www.callofduty.com/warzone" class="btn btn-primary fs-6 fw-bold ff">READ MORE</a>
              </p>
            </div>
          </div>
        </div>

        <div className='container p-2'>
          <div className='row featurette my-5 mx-2'>
            <div className='col-md-7 order-md-2'>
              <div class="card noborder text-bg-dark">
                <Image src={s1} height={550} class="card-img" alt="..." />

              </div>
            </div>
            <div className='col-md-5 order-md-1 text-center '>
              <div className='proh position-relative overflow-hidden  py-5  my-5 '>
                <div className="container ff  lh-base proh mx-auto py-5 my-5 ">
                  <p className="fs-1 fw-bold ">Get started any way you want </p>
                  <p className="fs-6 fw-bold ">Jump right into building with Bootstrap—use the CDN, install it via package manager, or download the source code.</p>

                </div>

              </div>

            </div>

          </div>

          <div className=' row featurette justify-content-center my-5 mx-2'>
            <div className='col-md-6 order-md-1 px-0'>
              <div class="card noborder text-bg-dark">
                <Image src={s2} height={650} class="card-img" alt="..." />
              </div>

            </div>
            <div className='col-md-6 order-md-2 text-center bg-black px-0'>
              <div className='card bg-black proh position-relative overflow-hidden  py-5  my-5 '>
                <div className="container ff fw lh-base proh mx-auto py-5 my-5 ">
                  <p className="fs-1 fw-bold ">Get started any way you want </p>
                  <p className="fs-5 fw-bold ">Jump right into building with Bootstrap—use the CDN, install it via package manager, or download the source code.</p>
                </div>
              </div>
            </div>

            <div className='col-md-6 order-md-4 px-0'>
              <div class="card noborder text-bg-dark">
                <Image src={s3} height={790} class="card-img" alt="..." />
              </div>

            </div>

            <div className='col-md-6 order-md-3 text-center bg-black px-0'>
              <div className='card bg-black proh position-relative overflow-hidden  py-5  my-5 '>
                <div className="container ff fw lh-base proh mx-auto py-5 my-5 ">
                  <p className="fs-1 fw-bold ">Build fast, responsive sites with Bootstrap</p>
                  <p className="fs-5 fw-bold ">Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins.</p>
                </div>
              </div>
            </div>


          </div>
        </div>

        <div className='bg3 justify-content-center text-center'>
          <div className=' py-5'>
            <Image className='my-5' src={imghead} height={50} />
            <p className="fs-1 fw-bold ">BOOTSTRAP® </p>
          </div>
          <div className='d-flex text-center flex-column m-2 flex-lg-row align-items-md-stretch justify-content-md-center gap-3 mb-4'>
            <div className='d-inline-block fs-5 px-2 ff'>
              <input className='form-control mx-2 ' placeholder="Enter Email Address">
              </input>

            </div>
            <div className=' d-inline-block fs-5 mx-2 ff' >
              <p className="lead1">
                <a href="https://www.callofduty.com/warzone" class="btn btn-primary fs-6 fw-bold ff">READ MORE</a>
              </p>
            </div>
          </div>

          <div className='container py-5 my-5'>
            <div class="row noborder">
              <div class="col-sm-4 p-4">
                <div class="card text-center al justify-content-center  text-black ff noborder">
                <Image src={imghead} class=""  height={30} alt="..."/>
                  <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 p-4">
                <div class="card text-black ff noborder">
                  <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 p-4">
                <div class="card text-black ff noborder">
                  <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

    </>
  )
}
