// import styles from '@/styles/index.css'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header1 from "../public/header2";
import TESTFOOT from "./testfoot"
import k from "../public/image/ak.jpg"
import a from "../public/image/ab.jpg"
import ac from "../public/image/ac.jpg"
import d from "../public/image/ad.jpg"
import c from "../public/image/ae.jpg"
import e from "../public/image/af.jpg"
import f from "../public/image/as.jpg"
import g from "../public/image/i.jpg"
import s from "../public/image/akk.jpg"
import x from "../public/image/45.jpg"
import Link from 'next/link'

export default function Ashika() {
    return (
        <>
            <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header1 />
            <main className='p-0 batta  align-content-center '>
                <div className='card '>

                    <Image className='p-0 img-fluid  _2yWxQtB7xJRsFyvEkRLyW' src={k} alt="#" />

                    <section className=' container accordion-body cam1 justify-content-center text-secondary PGIVj9NTYRWLNncBni330 px-4  ' >
                       
                            <h3 className='fs-4 card-title  text-secondary text-'>FEBRUARY 09, 2023</h3>
                            <h1 className=' fs-1 '>SEASON 02 TACTICAL OVERVIEW — ASHIKA ISLAND, DMZ, AND MORE</h1>
                        
                        <div className='text-secondary'>
                            <div > 
                                <p className=' fs-3'>The new Ashika Island map debuts in Battle Royale Resurgence and DMZ, the 1v1 Gulag returns, and more challenges and rewards await you in Season 02. Get a tactical grip on what s coming to <Link href=''>WarzoneTM 2.0</Link> when the season launches February 15.</p>
                                <ul className=' fs-5'>
                                    <li className=' fs-5 tag-item'>
                                        Mode Recon
                                    </li>
                                </ul>
                                <hr className='hr ' ></hr>
                                <h5 className=' fs-1'>Welcome to Warzone 2.0 Season 02</h5>
                                <p className=' fs-3'>Get ready to squad up and drop into Season 02 of Call of Duty®: Warzone™ 2.0, introducing the new Ashika Island map to Battle Royale and DMZ. Developed by High Moon Studios, Ashika Island brings players to a Resurgence-sized, centuries-old village in an archipelago, presenting all new risks and rewards across its many locales, bridges, districts, and waterways.</p>
                                <p className=' fs-3'>The new season will also feature the return of the 1v1 Gulag, a new AI Combatant, the Path of the Ronin seasonal event, new DMZ Faction Missions, and more. Season 02 launches on February 15. Read on for a tactical overview of everything coming to Warzone 2.0.</p>
                                <h5 className=' fs-1'> BATTLE ROYALE OVERVIEW</h5>
                                <Image className='imgg' src={a} height={500} width={1200} alt="#" />
                                <ul >
                                    <li className='lli fs-4'>Ashika Island Debuts with Resurgence. Explore a new environment with the launch of Ashika Island, debuting alongside Resurgence Battle Royale.</li>
                                    <li className='lli fs-4'>General Season 02 Changes. Season 02 introduces other changes across Ashika Island and Al Mazrah, including adjustments to your starting armor, Buy Stations, and Stronghold rewards.</li>
                                    <li className='lli fs-4'>1v1 Gulag. The 1v1 Gulag returns, including changes to the current Gulag map, ground loot, and starting Loadouts.</li>
                                    <li className='lli fs-4'>New Contract, Public Event, the Rusher, and More. Take on new challenges that will be added to Ashika Island throughout Season 02.</li>
                                </ul>
                                <h5 className=' fs-1'>Introducing Ashika Island</h5>
                                <Image className='imgg' src={ac} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <p className=' fs-3'>Welcome to Ashika Island, aka “Isle of the Sea Lion.” What was once planned as a resort destination is now under siege by Shadow Company, whose forces are looking for local members of the Ultranationalist Konni Group.</p>
                                <p className=' fs-3'>A compact, medium-sized map designed for Resurgence, Ashika Island includes various locales such as the Town Center, Beach Club, Tsuki Castle, Port Ashika, and river channels and bridges spread throughout the environment.</p>
                                <p className=' fs-3'>See our <Link href=''>Deep Dive on Ashika Island</Link> for a rundown of the new Resurgence map s seven major points of interest.</p>
                                <h5 className=' fs-1'>New Feature: Restore Honor</h5>
                                <Image className='imgg' src={d} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <p className=' fs-3'>Restore your honor and exact revenge against your enemy.</p>
                                <p className=' fs-3'>Once per match, Operators who fall on Ashika Island will drop a dog tag where they perished. If you or one of your squadmates picks up the dog tag, you ll be rewarded with a small Cash reward and a UAV Ping to scan the area for supplies and potentially the position of the enemy Operator who downed you.</p>
                                <p className=' fs-3'>Here are two strategies for this new feature:</p>
                                <ul>
                                    <li className='lli fs-4'>Truly Honorable. Heading straight for your dog tag after a redeployment is a smart way to get a head start on that fresh life. Alternatively, have a squadmate pick up that tag and call out nearby Supply Boxes so you can quickly build back that Loadout.</li>
                                    <li className='lli fs-4'>Dishonorable Bait. Given the advantage it provides, an enemy dog tag can be used to lure enemy teams into exposing their position. If you see a dog tag in the wild, consider taking an advantageous position near it and pick off any Operator who attempts to pick it up.</li>
                                </ul>
                                <p className=' fs-1'>A New Path to Riches</p>
                                <p className=' fs-3'>Season 02 balances the Battle Royale Cash economy for more consistent rewards when pursuing resources. The Cash payout for completing contracts has been slightly reduced, while the minimum value of Cash piles as ground loot has been increased to $800 and from cash registers it has been increased to $500.</p>
                                <Image className='imgg' src={c} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <p className=' fs-3'>Season 02 sees the return of the 1v1 Gulag. In this iteration, the Jailer s out; it s just you and the enemy player, with the return of the Domination-style control point as the overtime mechanic.</p>
                                <p className=' fs-3'> Operators will skirmish in an edited version of the current Gulag map that s better suited for 1v1 combat. Expect new ground loot and spawning Loadouts, including Assault Rifles, SMGs, and LMGs that change as the match progresses. Shotguns have been removed from the rotation.</p>
                                <p className=' fs-3'>Here s our advice for this updated Gulag:</p>
                                <ul>
                                    <li className='lli fs-4'>Practice makes perfect. Head into Call of Duty®: <a href=''>Modern Warfare® II Multiplayer</a> and try out a variety of Primary Weapons within those categories to learn their strengths and weaknesses. Although Operator health differs between Multiplayer and Battle Royale, learning how to control each weapon’s recoil and knowing their range can be crucial to surviving the Gulag. </li>
                                    <li className='lli fs-4'>Chuck those  nades. Remember that a Gulag Loadout also includes Lethal and Tactical Equipment. Use it to slightly damage or disorient opponents before dealing the eliminating blow with whatever given weapon.</li>
                                    <li className='lli fs-4'>More Cash: The Gulag now spawns Cash as ground loot to reward players who move around. If you can stall your opponent long enough, take time to pick up those stacks of Cash to make it easier to rebuild that Loadout on the redeploy. Also, Season 02 pays out a larger Cash reward to Gulag winners, so every W counts!</li>
                                </ul>

                                <p className=' fs-3'></p>
                                <h5 className=' fs-1'>New Exclusion Zone: Ashika Island</h5>
                                <div className='videooo justify-content-center'>
                                    <iframe className='videooo  justify-content-center' width="850" height="500" src="https://www.youtube.com/embed/y_Bn8Iw-iJk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                                </div>
                                <Image className='imgg' src={g} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <Image className='imgg' src={e} height={500} width={1200} alt="#" />

                                <p className=' fs-3'></p>
                                <p className=' fs-3'>Infiltrate Ashika Island, the third Exclusion Zone to be added to <Link href=''>DMZ</Link> after Al Mazrah and Building 21. Unlike Building 21, which requires that you first acquire a keycard, Ashika Island can be chosen as your DMZ destination at any time.</p>
                                <p className=' fs-3'>Infiltrating Ashika Island will be crucial to faction progress, with multiple missions across all factions involving Operators who must perform tasks on the island. However, you can also complete more generic missions that do not require deployment to a specific region on the island. If you find more success in eliminating enemies and gathering items on here compared to other exclusion zones, then feel free to drop back in here and use the new space to your advantage.</p>
                                <p className=' fs-3'>For more information about this reset, <Link href=''>read Infinity Wards DMZ blog here.</Link></p>
                                <p className=' fs-3'>Each player additionally begins the season with a fresh slate. Though you ll retain any permanent items you unlocked in the previous season, all earned Contraband and Keys will be reset from the inventory. Season 01 Faction Missions will be reset to make room for the new Season 02 Faction Missions, tasking players with assignments across all three Exclusion Zones.</p>
                                <h5 className=' fs-1'>Walk the Path of the Ronin</h5>
                                <Image className='imgg' src={s} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <Image className='imgg' src={x} height={500} width={1200} alt="#" />

                                <p className=' fs-3'></p>
                                <p className=' fs-3'>The Path of the Ronin Season 02 event launches with three challenges that can be completed in Modern Warfare II Multiplayer or Warzone 2.0.</p>
                                <h5 className=' fs-1'>Integrity</h5>
                                <p className=' fs-3'>Multiplayer: Win 15 matches in any Multiplayer game mode.</p>
                                <p className=' fs-3'>Warzone 2.0: Get five Top 10 finishes.</p>
                                <p className=' fs-3'>Advice: Get a great squad going — either with existing friends or by using the new social features — to tally up those wins in no time.</p>
                                <h5 className=' fs-1'>Honor</h5>
                                <p className=' fs-3'>Multiplayer: <Link href=''>Get 100 objective</Link> defense kills.</p>
                                <p className=' fs-3'>Warzone 2.0: Collect your dog tag (Restore Honor) 5 times.</p>
                                <p className=' fs-3'>Advice: For Multiplayer Operators, Hardpoint can be a great <Link href=''>game mode to sit on the point and eliminate enemies.</Link>As for Restoring Honor, it only needs to be done five times; do it only when you are certain enemies are not nearby and ready to pounce.</p>
                                <h5 className=' fs-1'>Sincerity</h5>
                                <p className=' fs-3'>Multiplayer:<Link href=''> Get 50 kills</Link> using Battle Rage.</p>
                                <p className=' fs-3'>Warzone 2.0: Complete five Assassination Contracts.</p>
                                <p className=' fs-3'>Expect more challenges to activate throughout the season, each gifting unique rewards upon completion, whether you perform the assigned Multiplayer or Battle Royale task. Complete all seven in either Warzone 2.0 or Modern Warfare II to unlock the Crossbow!</p>


                                <p className=' fs-3'>Stay frosty.</p>
                                <p className=' fs-3'>© 2019-2022 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY WARZONE, and MODERN WARFARE are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the property of their respective owners.</p>

                                <p className=' fs-3'>For more information, please visit<Link href=''> www.callofduty.com</Link> and <Link href=''>www.youtube.com</Link>/callofduty, and follow <Link href=' '>@Activision</Link> and <Link href=''>@CallofDuty</Link> on Twitter, Instagram, and Facebook.</p>





                                <br></br>
                                <br></br>
                                <hr className='hr' ></hr>

                                <div>

                                    <span className='spann'>
                                        <Link className='spann' href='/'>
                                            <span>Back to Blog Index</span>
                                        </Link>
                                    </span>
                                </div>

                            </div>
                        </div>
                    </section>



                </div>
                <hr className='hr' ></hr>

                <TESTFOOT />
            </main>
        </>
    )
}

