// import styles from '@/styles/index.css'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header0 from "../public/image/header"
import bat from "../public/image/bat.jpg"
import batt from "../public/image/batt.jpg"
import b33 from "../public/image/b3.jpg"
import b44 from "../public/image/b4.jpg"
import b55 from "../public/image/b5.jpg"
import a from "../public/image/2222.png"
import b from "../public/image/kkpp.jpg"
import Link from 'next/link'
import n from "../public/image/kz.jpg"
import Header1 from "../public/header2";

import TESTFOOT from "./testfoot"




export default function BATTLE() {
    return (
        <>
            <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header1 />
            <main className='p-0 batta align-content-center '>
                <div className=' card'>

                    <Image className='p-0 img-fluid _2yWxQtB7xJRsFyvEkRLyW_' src={bat} alt="#" />

                    <section className='  container-xxlg accordion-body cam1  px-4  justify-content-center PGIVj9NTYRWLNncBni330'>
                       
                            <h3 className='fs-4   text-secondary'>FEBRUARY 14, 2023</h3>
                            <h1 className=' fs-1 card-title'> INTRODUCING THE BATTLE PASS AND BUNDLES FOR CALL OF DUTY®</h1>
                        
                        <div className='text-secondary'>
                            <div>
                                <ul>
                                    <li className='tag-item fs-5'>
                                        NEWS
                                    </li>
                                    <li className='tag-item fs-5'>
                                        Mode Recon
                                    </li>
                                </ul>

                                <h5 className=' fs-1'>FORGE YOUR PATH IN SEASON 02</h5>
                                <p className=' fs-3'>Even in the face of chaos, the modern warrior walks an honorable path, one of integrity, respect, courage, honor, compassion, sincerity, and loyalty. Learning these ways of the warrior will separate the elite Operators from the rest of the pack, as the global conflict calls for a swift resurgence to an island off the coast of Japan. </p>
                                <Image className='imgg' src={b} height={500} width={1200} alt="#" />

                                <p className=' fs-3'>The <Link href=''>new Battle Pass for Season 02</Link> features 100+ rewards across 20 Sectors, including three new functional weapons and the Operator Ronin The Season 02 Battle Pass launches at the start of the season on February 15. Upgrade to the full Battle Pass for access to all of Season 02 s Battle Pass items or purchase the Battle Pass Bundle to earn additional Battle Token Tier Skips and get a head start on conquering the map</p>
                                <p className=' fs-3'>Players who purchase the Season 02 Battle Pass or Battle Pass Bundle will gain immediate access to the B0 Bonus Sector featuring Ronin </p>
                                <div className='justify-content-center'>
                                    <iframe className='videooo' width="850" height="500" src="https://www.youtube.com/embed/dm7cJsTXm0g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                                </div>
                                <p className=' fs-3'>After the fall of Armistice, it wasn t long until inter-factional wars starting spilli fs-4ng into neighboring areas such as Al Mazrah. As a masterless mercenary, Ronin took it upon himself, using his skills in reconnaissance and sabotage, to maintain balance between the factions while taking up a new code:</p>
                                <p className=' fs-3'>An ex-Special Forces officer, Daniel “Ronin” Shinoda s skills in unconventional warfare were in high demand  during the Verdansk conflict. In 2019, the “one-man-army” volunteered for Armistice, a multi-national force that opposed emerging threats in the region. He believed this force would restore balance to the war-ravaged lands. Instead, he saw it descend into chaos.</p>
                                <h5 className=' fs-1'>Purchase the Battle Pass to Unlock Bonus Sector B0, Ronin</h5>
                                <Image className='imgg' src={batt} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <p className=' fs-3'>© 2023 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY WARZONE, and MODERN WARFARE are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the property of their respective owners.</p>
                                <p className=' fs-3'>For more information, please visit <Link href=''>www.callofduty.com</Link> and <Link href=''>www.youtube.com/callofduty</Link>, and follow <Link href=''>@Activision</Link> and <Link href=''>@CallofDuty on Twitter, Instagram, and Facebook.</Link></p>
                                <h5 className=' fs-1'>New HVT Operator Skins at Sectors B3, B8, B10</h5>
                                <Image className='imgg' src={b33} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>

                                <p className=' fs-3'>New Sectors mean new tactical kits for several Operators, all prepared to drop in and make their mark on Ashika Island and Modern Warfare I s additional Season 02 Multiplayer maps Dome (Core) and Zaya Observatory (Battle Map), Al Malik International  (Battle Map), and Valderas Museum (Core).</p>
                                <p className=' fs-3'>Dressed in full tactical gear, a mesh hood, and gloves, König is ready to take the fight wherever it may lead the KorTac forces. This Sector is right next to the start, making it an easy unlock.</p>
                                <h5 className=' fs-1'>Dual Kodachis Melee Weapon — (Sector B13, HVT, Free)</h5>
                                <Image className='imgg' src={b44} height={500} width={1200} alt="#" />
                                <h5 className=' fs-1'>ISO Hemlock Assault Rifle — ISO Platform (Sector B11, HVT, Free)</h5>
                                <Image className='imgg' src={b55} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>

                                <p className=' fs-3'>Season 02 continues the run of Bundles themed around the seven vices. The first, VII: Envy, features the glowing eyed “Covetous” Operator Skin and two Weapon Blueprints, a Vehicle Skin, a Weapon Charm, a Sticker, and an animated Emblem. VII: Gluttony offers “The Hunger” Operator Skin with two Weapon Blueprints, a Vehicle Skin, a Weapon Charm, a Gun Screen, a Sticker, a Vinyl, and an Emblem.</p>
                                <p className=' fs-3'>Kleo prepares for undercover ops in this Operator Skin featuring pauldrons, a hood for all-weather target acquisition, and a red and black filtered mask.</p>
                                <h5 className=' fs-1'>Dual Kodachis: Melee</h5>
                                <ul>
                                    <li className='lli fs-4' >A powerful melee weapon that can quickly move towards a target with a longer-range attack. Each swipe has an impressive range and faster forward motion towards enemies compared to the Knife melee weapon, though this comes at a slight cost, a slower strafe and sprint speed.
                                    </li>
                                    <li className='lli fs-4'>Can be acquired for free via the Season 02 Battle Pass.</li>
                                </ul>
                                <Image className='imgg' src={a} height={500} width={1200} alt="#" />


                                <br></br>
                                <br></br>



                                <p className=' fs-3'>© 2019-2022 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY WARZONE, and MODERN WARFARE are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the property of their respective owners.</p>
                                <h5 className=' fs-1'>Complete the Map for Victory Sector Rewards</h5>
                                <Image className='imgg' src={n} height={500} width={1200} alt="#" />
                                <p className=' fs-3'></p>
                                <p className=' fs-3'>Conquer all 20 Sectors to get 100% map completion and access to the final Victory Sector, which features the following items:</p>
                                <p className=' fs-3'>“The Peak” Ronin Operator Skin</p>
                                <p className=' fs-3'>Ronin operates at peak performance in this all-black tactical kit, featuring short sleeves, tattoos, and samurai-inspired shoulder armor. Equip this kit to show off your unflinching dedication to victory.</p>
                                <p className=' fs-3'>300 COD Points

                                </p>


                                <p className=' fs-3'>Save up for the next Battle Pass or put those points toward the purchase of a new Store Bundle.

                                </p>
                                <p className=' fs-3'>For more information, please visit<Link href=''> www.callofduty.com</Link> and <Link href=''>www.youtube.com</Link>/callofduty, and follow <Link href=' '>@Activision</Link> and <Link href=''>@CallofDuty</Link> on Twitter, Instagram, and Facebook.</p>

                                <hr className='hr' ></hr>



                                <div>
                                    <span className='spann'>
                                        <Link className='spann' href='/'>
                                            <span>Back to Blog Index</span>
                                        </Link>
                                    </span>
                                </div>

                            </div>
                        </div>
                    </section>



                </div>
                <hr className='hr' ></hr>

                <TESTFOOT />
            </main>







        </>
    )
}