import img8 from "../public/image/w2.jpg"
import zaya1 from "../public/image/zaya.jpg"
import bg1 from "../public/image/bg.jpg"
import Image from 'next/image'
import Sidebar1 from "../public/componant/Sideber.js"
// import styles from '@/styles/globals.css'


export default function Categoryr() {
    return (
        <>
            <head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="public\image\logo.jpg" />
            </head>

            {/* <Sidebar1/> */}

            <nav class="navbar fixed-top navbarr row-4">
                <div className=" Ima col-1 ">
                    <Image src={img8} alt="" height="100" /></div>
                <div class="container col-8 ">
                    <div className="col ">
                        <input className="  search col-2 "
                            placeholder="Search.... "
                            onChange={(event) => {
                                setsearch(event.target.value)
                            }}
                        />
                    </div>

                    <div class="col-md-2 ">
                        <button type="button" class="btn btn-primary me-2 but "><a href="/login" className="a">SIGN IN</a></button>
                        <button type="button" class="btn btn-secondary but"><a href="/register " className="a">SIGN UP</a></button>
                    </div>


                </div>
            </nav>
            <div className="bgg">
                <div className="bgContent">
                    <div className="bg-image">
                        <div className="content ">
                            <div className="contentLayoutContainer ">
                                <div class="content2 ">
                                    <h2>UP TO 32v32</h2>
                                    <h1> BATTLE MAPS </h1>
                                    <p>Call of Duty: Next and the Open Beta are showcasing....</p>
                                    <div className="contentButton">
                                        <div className="jsx-1751277314 h-buttons-group">
                                            <span className=" h-buttons-group-button">
                                                <a href="">
                                                    <button type="button" className="buttong">go to collection</button>
                                                </a>
                                            </span>
                                        </div>

                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
           <div className="contentBelowBanner___1csYL">
             <section className="hover contentAreaNoPadding___2M1NZ">
                <a className="titlePadding___2lp1P" href="">
                    <span>NEW Gun</span>
                </a>
                <div className="horizontalScroll___1O_E3">
                    {/* <button type="button" className="sideArrow___1s2uV sideArrowRight___3W9nJ">
                        
                        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                            <path d="M29 44L13 24L29 4"></path>
                            </svg>
                        
                    </button> */}
                    <div className="row___2fBWZ">
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={zaya1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={bg1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={zaya1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>   
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={zaya1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li> 
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                    </div>
                </div>
             </section>







             <section className="hover contentAreaNoPadding___2M1NZ">
                <a className="titlePadding___2lp1P" href="">
                    <span>NEW Car</span>
                </a>
                <div className="horizontalScroll___1O_E3">
                    {/* <button type="button" className="sideArrow___1s2uV sideArrowRight___3W9nJ">
                        
                        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                            <path d="M29 44L13 24L29 4"></path>
                            </svg>
                        
                    </button> */}
                    <div className="row___2fBWZ">
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={bg1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={zaya1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>   
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li> 
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                    </div>
                </div>
             </section>


             <section className="hover contentAreaNoPadding___2M1NZ">
                <a className="titlePadding___2lp1P" href="">
                    <span>NEW CHARACTER </span>
                </a>
                <div className="horizontalScroll___1O_E3">
                    {/* <button type="button" className="sideArrow___1s2uV sideArrowRight___3W9nJ">
                        
                        <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                            <path d="M29 44L13 24L29 4"></path>
                            </svg>
                        
                    </button> */}
                    <div className="row___2fBWZ">
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={bg1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={zaya1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>   
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li> 
                        <li className="cell___3sPIk">
                            <div className="cellGuts___1TMU_">
                                <a href="/megascans/home?assetId=wkfkfbt">
                                <span className="clickableBox___1HFCs">
                                    <div className="boxWithAspectRatioContainer___2hILe">
                                        <div className="boxWithAspectRatioInner___2gUvu">
                                            <div className="css-1k8lzl2">
                                                <div>
                                                    <Image className="css-2pknc3" src={1} alt=""/> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </span>
                                </a>
                            </div>
                        </li>
                    </div>
                </div>
             </section>


             </div>




        </>

    )
}

