import Head from "next/head"
import Image from 'next/image';
import cam1 from "../public/image/comu1.jpg"
import cam2 from "../public/image/comu2.jpg"
import Header1 from "../public/header2";
import TESTFOOT from "./testfoot"
import Link from 'next/link';

export default function cam() {
    return (
        <>
            <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header1 />
            <body>
                <div className="container accordion-body cam1">
                    <div className="card cam1">
                        <Image className=" accordion-flush imgg" src={cam1} height={500} width={1200} alt="#" ></Image>
                        <div className="card-body">
                            <h3 className="card-title">THE PATH TO SEASON 02 - CALL OF DUTY®: MODERN WARFARE® II
                                AND WARZONE™ 2.0 COMMUNITY UPDATE</h3>
                            <p className="card-text camtextsm">Hello Call of Duty Community!
                                We want to share some updates coming to Season 02 for Multiplayer, DMZ and Battle Royale.
                                Information on new features, maps, modes, and more will be shared over the coming weeks.
                                All the changes outlined in this blog will be further detailed along with new content in
                                Call of Duty: Modern Warfare II and Warzone 2.0 Patch Notes to be released prior to the
                                season launch on February 15, 2023.</p>
                            <p className="card-text text-lg-end">JANUARY 25, 2023 by Infinity Ward</p>
                        </div>
                    </div>

                </div>
                <hr className="divider" />

                <div className="container accordion-body cam1">
                    <div className="card cam1">
                        <div className="card-body">
                            <h3 className=" card-title textcam ">
                                Global Changes
                            </h3>
                        </div>
                        <Image className=" accordion-flush imgg" src={cam2} height={500} width={1200} alt="#" ></Image>
                        <div className="card-body">
                            <h4 className="card-title">Crashes and Stability</h4>
                            <p className="card-text camtextsm">We remain dedicated to improving the overall stability and performance of our games,
                                including reduced crashes across all platforms and titles.
                                Expect the Season 02 Patch Notes to further detail specific bug fixes and changes ahead of February 15th.
                            </p>
                            <h4 className="card-title">Audio (Global)</h4>
                            <p className="card-text camtextsm">Data suggests that some PC Players may be experiencing audio issues
                                due to discrepancies in the number of channels they are outputting. We added an option to force
                                PC to stereo output; please be sure to check Windows and in-game audio settings are set correctly in
                                accordance with your listening environment.

                            </p>
                            <p className="card-text camtextsm"> Investigation into player reports regarding audio
                                led us to identifying a previously unknown issue impacting occlusion across the game. Audio
                                occlusion is a filter that is applied based on the type of material that an object or structure
                                is composed of, primarily based on its thickness and how it blocks the full frequency of the
                                sound. Only large structural objects should apply the filter, but we found some small items like
                                a stapler or a pile of rags on the ground that were causing the filter to turn on when it
                                should not have. For example, a wastebasket that was tagged with the incorrect material may
                                have occluded the sound like it was behind a wall making the sound more difficult for a
                                player to hear. This issue will be addressed in the Season 02 update and we continue to
                                work on fixes and new audio features to better our player experience.</p>

                        </div>
                        <div className="card-body">
                            <h4 className="card-title">Crashes and Stability</h4>
                            <p className="card-text camtextsm">We remain dedicated to improving the overall stability and performance of our games,
                                including reduced crashes across all platforms and titles.
                                Expect the Season 02 Patch Notes to further detail specific bug fixes and changes ahead of February 15th.
                            </p>
                            <h4 className="card-title">Audio (Global)</h4>
                            <p className="card-text camtextsm">Data suggests that some PC Players may be experiencing audio issues
                                due to discrepancies in the number of channels they are outputting. We added an option to force
                                PC to stereo output; please be sure to check Windows and in-game audio settings are set correctly in
                                accordance with your listening environment.

                            </p>
                            <p className="card-text camtextsm"> Investigation into player reports regarding audio
                                led us to identifying a previously unknown issue impacting occlusion across the game. Audio
                                occlusion is a filter that is applied based on the type of material that an object or structure
                                is composed of, primarily based on its thickness and how it blocks the full frequency of the
                                sound. Only large structural objects should apply the filter, but we found some small items like
                                a stapler or a pile of rags on the ground that were causing the filter to turn on when it
                                should not have. For example, a wastebasket that was tagged with the incorrect material may
                                have occluded the sound like it was behind a wall making the sound more difficult for a
                                player to hear. This issue will be addressed in the Season 02 update and we continue to
                                work on fixes and new audio features to better our player experience.</p>

                        </div>
                        <hr className="divider" />
                        <div className="card-body">
                            <h3 className="card-title textcam ">
                                Battle Royale
                            </h3>
                        </div>

                        <Image className=" accordion-flush imgg  text-e" src={cam2} height={500} width={1200} alt="#" ></Image>
                        <div className="card-body">
                            <h4 className="card-title">The Gulag</h4>
                            <p className="card-text camtextsm">1v1 Gulag will be returning with the launch of Season 02.
                                With this change, Players will see the return of
                                the original Warzone overtime mechanic - the Domination-style flag control point - in place of the Jailer. </p>
                            <p className="card-text camtextsm">In order to bring this change online sooner -
                                we have edited the existing Season 01 Gulag for better 1v1 combat, but are actively working on a dedicated 1v1 map for future seasons.</p>
                            <p className="card-text camtextsm">We’ve also made some logistical changes to the Gulag experience. Ground loot
                                has been revisited as well as the Loadouts that Players will spawn in with. We’ve updated the pool to
                                include Assault Rifles, Submachine Guns, and Light Machine Guns as Primary Weapons as the Circles progress.
                                Shotguns have been removed from the rotation, while Handguns will remain available as Secondary Weapons.
                            </p>
                            <p className="card-text camtextsm">
                                For those leaving the arena victorious, the Gulag will grant a larger Cash reward to players.
                                This change to cash will allow redeploying players to get back on their feet a bit faster.
                            </p>

                            <p className="card-text camtextsm">
                                Alongside increased victory Cash rewards mentioned in the previous section, the Gulag will now spawn
                                Cash as ground loot to encourage and reward Players willing to prowl the arena.
                            </p>
                            <h4 className="card-title">Cash Economy</h4>
                            <p className="card-text camtextsm">In addition to the cash changes to the Gulag outlined above,
                                we are balancing the Battle Royale economy with a slight reduction to cash rewards for completing
                                contracts. Additionally, we are increasing the lowest value of Cash piles from ground loot to $800
                                and from Cash Registers to $500 (previously $100 minimum).</p>
                            <p className="card-text camtextsm"> In addition to this, Cash can be acquired via ground loot, containers,
                                and white Stronghold Supply Boxes throughout Al Mazrah, but can no longer be found in basic and legendary
                                Supply Boxes.
                            </p>
                            <p className="card-text camtextsm">This redistribution should make for quicker, more consistent gameplay
                                in the pursuit of resources.</p>
                            <h4 className="card-title">Loot & Inventory</h4>
                            <p className="card-text camtextsm">
                                As announced last week, we’re shifting away from loot windows/menus to floating loot that will now drop
                                out of all containers in the world, similar to loot from Supply Boxes.
                            </p>
                            <p className="card-text camtextsm">
                                This change is intended to improve the pace of gameplay by minimizing time spent navigating the UI and
                                getting Players back in the action faster.
                            </p>
                            <p className="card-text camtextsm">
                                We were excited to see the new Backpack system give Players the agency to customize their inventory
                                for a desired playstyle or role within a Squad. In our continued effort to balance engagements,
                                Medium/Large Backpacks will no longer be available and eliminated Players will drop loot onto the
                                ground rather than loot-filled Backpacks. Every Player will have the same Backpack throughout the
                                entire game which will subsequently reduce the impact of stacking medical supplies, Equipment, and
                                Killstreaks. We will continue to look for feedback and provide updates that streamline the looting
                                experience for everyone.
                            </p>

                        </div>
                        
                    </div>
                    <div className="cam2">
                        <Link href="/" className="btnnn card-title text-center justify-content-end ">back to home</Link>
                    </div>
                    <hr className="divider" />
                </div>

            </body>

            <TESTFOOT />

        </>
    )
}