import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import img1 from "../public/image/callbg.jpg"
import Header0 from "../public/image/header"
import img10 from "../public/image/black-panther.jpg"
import img11 from "../public/image/jumanji.jpg"
import img12 from "../public/image/q.jpg"
import img13 from "../public/image/wwww.jpg"
import a from "../public/image/a.jpg"
import b from "../public/image/b.jpg"
import c from "../public/image/c.jpg"
import d from "../public/image/d.jpg"
import e from "../public/image/e.jpg"
import f from "../public/image/f.jpg"
import g from "../public/image/g.jpg"
import h from "../public/image/h.jpg"
import aa from "../public/image/aa.jpg"
import vv from "../public/image/4.png"
import v from "../public/image/5.png"
import vvv from "../public/image/6.png"
import vvvv from "../public/image/7.png"
import bb from "../public/image/8.jpg"
import dd from "../public/image/44.png"
import ff from "../public/image/4.png"
import kk from "../public/image/22.png"
import ag from "../public/image/ag.jpg"
import ney from "../public/image/Ney.png"
import po from "../public/image/pop.png"
import me from "../public/image/messi.jpg"
import wo from "../public/image/wom.jpg"
import TESTFOOT from "./testfoot"
import na from "../public/image/COD.jpg"
import cyy from "../public/image/cy.jpg"
function SecondHalfImages() {
  return (
    <>
      <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#" />
      <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#" />
      {/* add more images */}
    </>
  );
}





// import styles from '@/styles/index.css'

// const inter = Inter({ subsets: ['latin'] })
//asdasghjdgashjdgjagdj
export default function Home() {
  // const card = [
  //   {
  //     image: img,
  //     title: "cute",
  //     text: "dhjshdjshdjk",
  //     dow: "download"
  //   },
  //   {
  //     image: img,
  //     title: "Card title",
  //     text: "dhjshdjshdjk",
  //     dow: "download"
  //   }
  //   , {
  //     image: img,
  //     title: "Card title",
  //     text: "dhjshdjshdjk",
  //     dow: "download"
  //   }

  // ]

  return (
    <div>
      <Head>
        <title>Call of DUTY®</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header0 />
      {/* <section className='css-bfjn8h'>
        
        <div className= "css-j34mpb"></div>
        <video autoPlay loop muted className='css-dq71mr' poster="https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/body/mwii/MWII-LAUNCH-MP-003-.jpg" id="vid" >
          <source src="https://www.callofduty.com/cdn/wzm/videos/wzm-cinematic.mp4" type="video/mp4"></source>
          </video>
      </section> */}
      
      
      
      
      <div>


        <div className="centered">
          <p className="hh1">MODERN WARFARE II THE NEW CALL OF DUTY®  WARZONETM 2.0</p>
          <p className="h3 ">  MAP IN SEASON 02 OF CALL OF DUTY®: WARZONE™ </p>
          <p className="lead1">
            <a href="https://www.callofduty.com/warzone" class="btn btn-primary lead2">READ MORE</a>
          </p>
        </div>
      </div>






      <div className="  css-12eyf74 " data-reactid="260" >
        <div className="css-1mesriy" data-reactid="261">
          <section className='css-zvkjbf'>
            <div className="css-11ls71j">
              <a className='css-b06u1v' href=''>
                <div className="css-1p3f1wx">
                  <div className='css-2x76mi'>
                    <h1>WARFARE® II </h1>
                    <h3>RELOADED — HIMMELMATT EXPO MAP INTEL</h3>
                  </div>
                </div>
              </a>
            </div>
          </section>
        </div>


        <div className="css-1mesriy" data-reactid="270">
          <section className='css-1ugfr5s'>
            <div className="css-11ls71j">
              <a className='css-b06u1v' href=''>
                <div className="css-1p3f1wx">
                  <div className='css-2x76mi'>
                    <h1>Full AWARENES</h1>
                    <h3>YOUR GET IN THERE, SOLDIER</h3>
                  </div>
                </div>
              </a>
            </div>
          </section>
        </div>

        <div className="css-1mesriy" data-reactid="270">
          <section className='css-1ugfr5'>
            <div className="css-11ls71j">
              <a className='css-b06u1v' href=''>
                <div className="css-1p3f1wx">
                  <div className='css-2x76mi'>
                    <h1>SKINS In MODERN WARFARE 2</h1>
                    <h3>Messi, Pogba & Neymar Skins Release Date For MW2 & Warzone 2</h3>
                  </div>
                </div>
              </a>
            </div>
          </section>
        </div>
      </div>





      <section data-reactid="288" data-css-oqffr1>
        <div className="ccss-1mm9hv1" data-reactid="289"></div>
        <div className="css-z6wpf2">Modern Warfare FC | Call of Duty: Modern Warfare II & Warzone 2.0</div>
        <div className='css-9hvpez' data-reactid="291" >
          <div className='css-9hvv' data-reactid="291">
            <iframe width="1000" height="550" src="https://www.youtube.com/embed/EwoXZw1RKUA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </div>
        </div>
      </section>




      
     


      <section className="css-g7jrk6" >
        <div id="xxx" className="css-14ka3k5" >
          <div className="false">
            <div className="css-1gtlguw">
              <span className='css-1i1szvg'>featured in MODERN  Warzone</span>
              <div className='css-a9x5ro' >
                <div className='css active' >
                <Image className='css-15lzgyg ' src={me} height={699} width={300} alt="#" />
                  <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={ney} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={kk} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={ff} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={po} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={dd} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={v} height={699} width={300} alt="#"/>
                  {/* //เพื่อต่อ */}
                  <Image className='css-15lzgyg' src={po} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={dd} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={po} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg ' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={ney} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={kk} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={ff} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={po} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg ' src={me} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={vvv} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={dd} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={ney} height={699} width={300} alt="#"/>
                  <Image className='css-15lzgyg' src={me} height={699} width={300} alt="#"/>



                  






                </div>


              </div>


            </div>

          </div>
        </div>

      </section>

      



      <section className='css-1welzgn'>
        <div id="xxx" className=' css-fmpy9'>
          <div className='css-1d9yaxp'>
            <div className='css-11pgmqa'>
              <div>
                <div className='css-nvbtbj'>WARZONE BLOG</div>
                <div className='css-1x1bg8g'>THE LATEST NEWS WHAT NEW</div>
              </div>
              <div className='css-u0x0j8'>
                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en ">
                      <div className='css-1c6tbi4'></div>
                      <div className='css-1mm9hv1 '>
                        <span className='css-137ghns'>SEPTEMBER 15, 2022</span>
                        <h1 className='css-141i1s7'> NEXT: ANNOUNCING CALL OF DUTY®: WARZONE™</h1>
                      </div>
                    </section>
                  </a>
                </div>

                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en">
                      <div className='css-1osijr9'></div>
                      <div className='css-1mm9hv1'>
                        <span className='css-137ghns'>FEBRUARY 14, 2023</span>
                        <h1 className='css-141i1s7'>  BATTLE PASS AND BUNDLES FOR CALL OF DUTY®</h1>
                      </div>
                    </section>
                  </a>
                </div>

                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en">
                      <div className='css-12simwh'></div>
                      <div className='css-1mm9hv1'>
                        <span className='css-137ghns'>DECEMBER 13, 2022</span>
                        <h1 className='css-141i1s7'> WHAT TO KNOW ABOUT CALL OF DUTY®:  LIVE DECEMBER 14-23</h1>
                      </div>
                    </section>
                  </a>
                </div>


                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en">
                      <div className='css-1pkevbo'></div>
                      <div className='css-1mm9hv1'>
                        <span className='css-137ghns'>FEBRUARY 09, 2023</span>
                        <h1 className='css-141i1s7'>SEASON 02 : OVERVIEW ASHIKA ISLAND, DMZ, AND MORE</h1>
                      </div>
                    </section>
                  </a>
                </div>



                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en">
                      <div className='css-1ke7anx'></div>
                      <div className='css-1mm9hv1'>
                        <span className='css-137ghns'>FEBRUARY 23, 2023</span>
                        <h1 className='css-141i1s7'>SUPPORT VETERANS WITH THE CALL OF DUTY ENDOWMENT (C.O.D.E.)</h1>
                      </div>
                    </section>
                  </a>
                </div>

                <div className='css-1xvx2me'>
                  <a className='css-1dnwvu3' href='' >
                    <section class="css-6os4en">
                      <div className='css-871aqv'></div>
                      <div className='css-1mm9hv1'>
                        <span className='css-137ghns'>JANUARY 25, 2023</span>
                        <h1 className='css-141i1s7'>THE PATH TO SEASON 02 COMMUNITY UPDATE</h1>
                      </div>
                    </section>
                  </a>
                </div>



              </div>
            </div>
          </div>
          <footer className='css-h7dop2'>
            <div className='css-1k83v4m'>
              <span className="css-1hqh14k">
                <span className='css-102rvdm' >
                  <a className='css-10800iq' href=''>
                    <span className='label'> GO TO BLOG.</span>
                  </a>
                </span>
              </span>
            </div>
          </footer >
        </div>
      </section>


      <section className='css-1fxl72w'>
        <div className='css-j34mpb'> <video autoPlay loop muted className='css-dq71mr' poster="https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/body/mwii/MWII-LAUNCH-MP-003-.jpg" id="vid" >
          <source src="https://www.callofduty.com/cdn/wzm/videos/wzm-cinematic.mp4" type="video/mp4"></source>
          </video>
        </div>
       
        <div className='css-1iwdce8'>
          <span className='css-u36hqk'></span>
          <h1 className='css-kovv1o'>
            EVERYTHING YOU NEED TO KNOW ABOUT SEASON 02 RELOADED
          <br></br>
              for  Season 02 of Call of Duty®: Warzone™ 2.0
          </h1>
          <div>
          <span className='css-1ojjt41'>
            <span >
              <a className="css-1lmvk87" href=''>Learn More</a>
            </span>

          </span>
        </div>

        </div>

        



        


<br></br>
<br></br>
      <TESTFOOT/>

    </div>
  )
}
