// import styles from '@/styles/index.css'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header0 from "../public/image/header"
import TESTFOOT from "./testfoot"
import nee from "../public/image/ne.jpg"
import neee from "../public/image/nee.jpg"
import naa from "../public/image/na.jpg"
import na from "../public/image/naa.jpg"
import aan from "../public/image/an.jpg"
import b from "../public/image/ann.jpg"
import av from "../public/image/at.jpg"
import Link from 'next/link'
import Header1 from "../public/header2";


export default function Next() {
    return (
        <>
        <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header1 />

        <div className='p-0 batta  align-content-center '> 
            <article className='card _2jwgMFDkSKSr-foNIF_7f9'>

                <Image className='p-0  img-fluid  _2yWxQtB7xJRsFyvEkRLyW' src={neee} alt="#" />

                <section className='PGIVj9NTYRWLNncBni330 container-xxlg accordion-body cam1 justify-content-center'>
                    
                        <h3 className='fs-4 card-title _2rgIsi3tJYjXp_0uWKfrBZ'>FEBRUARY 14, 2023</h3>
                       <h1 className=' fs-1 '> NEXT: ANNOUNCING CALL OF DUTY®: WARZONE™ MOBILE, REDEFINING BATTLE ROYALE FOR GAMERS ON THE GO</h1>
                 
                    <div className='nOk1K0s0zezhHodo4OuM3'>
                        <div>
                        <ul>
                                <li className='tag-item fs-5'>
                                    Mode Recon
                                </li>
                            </ul>
                           <p className=' fs-3 '>Call of Duty®: Warzone™ Mobile redefines Battle Royale on the go with an all-new unique <Link  href=''>Call of Duty</Link>:Warzone experience for 120 live players and cross-progression with Call of Duty®: Warzone™ 2.0 and Call of Duty®: Modern Warfare® II. Pre-register now!</p>
                            <hr className='hr' ></hr>
                           <h5 className=' fs-1 '>Announcing Call of Duty®: Warzone™ Mobile</h5>
                           <p className=' fs-3 '>Just revealed at Call of Duty: Next, Call of Duty®: Warzone™ Mobile will join Call of Duty®: Modern Warfare® II and Call of Duty®: Warzone™ 2.0 to usher in a new era of Call of Duty®.  With a thrilling Battle Royale gameplay, authentic content like Operators, Weapons, locations, and Call of Duty: Warzone combat with up to 120 live players in a match on mobile, the free-to-play Call of Duty: Warzone Mobile is set to redefine the Battle Royale on the go.  </p>
                           <p className=' fs-3 '>Leveraging new unified technology across Call of Duty: Modern Warfare II, Call of Duty: Warzone 2.0 and Call of Duty: Warzone Mobile, players can share many social features (like friends and chat channels) and cross-progression enabling a shared Battle Pass and more for a connected Call of Duty experience. </p>
                           <p className=' fs-3 '>Built for mobile devices to ensure an amazing handheld experience, Call of Duty: Warzone Mobile is set to feature mobile-specific events, playlists, and content as well as deep control customization options to support both Call of Duty veterans and new recruits alike.</p>
                            <Image  className='imgg'  src={naa}  height={500} width={1200} alt="#" />
                           <p className=' fs-3 '>In collaboration with Call of Duty studios and technology teams across Activision, Call of Duty: Warzone Mobile is being co-developed by a multi-studio mobile organization that includes teams from Activision Shanghai Studio, Beenox, Digital Legends, and Solid State Studios.</p>
                           <p className=' fs-3 '>Need a deeper dive into the game? Be sure you re watching the Official Call of Duty Twitch® Channel or Call of Duty YouTube® Channel for real-time gameplay or a rewatching of the Next event, then read on for further intel:</p>
                           <p className=' fs-3 '>Need a deeper dive into the game? Be sure you re watching the Official <Link href=''>Call of Duty Twitch® Channel</Link> or <Link href=''>Call of Duty YouTube® Channel</Link> for real-time gameplay or a rewatching of the Next event, then read on for further intel:</p>
                           <h5 className=' fs-1 '>Details: The Call of Duty: Warzone Experience on Your Mobile Device</h5>
                            <Image  className='imgg'  src={na}  height={500} width={1200} alt="#" />
                            <br></br>
                            <br></br>
                            <Image  className='imgg'  src={aan}  height={500} width={1200} alt="#" />                            
                            <br></br>
                            <br></br>
                           <p className=' fs-3 '>What should you expect when Call of Duty: Warzone Mobile launches next year? A return to a familiar battleground, using new weaponry, uniting Call of Duty: Warzone Mobile to Call of Duty: Modern Warfare II and Call of Duty: Warzone 2.0. Here s the initial intel you need to know now:</p>
                           <p className=' fs-3 '>Every aspect of the games development is customized for mobile gamers:</p>
                            <ul>
                                <li className='lii fs-4'><Link href=''>Head to the Google Play Store now to pre-register!</Link></li>
                                <li  className='lii fs-4'>Built for the Way You Play: With deep control customization options for mobile devices, you re able to pick up and play no matter your skill level. Mobile gaming professionals, PC and console players who want to sneak in a few more matches, and even new recruits who just need a little extra help getting into the flow of the game: We have you covered.</li>
                                <li className='lii fs-4'>Customized Content: The game will also feature a robust selection of mobile-specific events, customized playlists, and a variety of special content that you can t find anywhere else.</li>
                                <li className='lii fs-4'>Mobile Optimization: Everything from movement, aiming and weapon handling, to physics, animations and sound have been optimized for mobile gaming in order to deliver the ultimate accuracy, authenticity and performance you expect from Call of Duty.</li>
                            </ul>
                           <h5 className=' fs-1 '>Pre-register Now for in-game Rewards!</h5>
                            <Image  className='imgg'  src={b}  height={500} width={1200} alt="#" />    
                            
                            
                            
                            
                            <br></br>
                            <br></br>
                            <hr className='hr' ></hr>

                            <div>
                                <span className='spann'>
                                    <Link className='spann' href='/'>
                                        <span>Back to Blog Index</span>
                                    </Link>
                                </span>
                            </div>
                            
                        </div>
                    </div>
                </section>
               


            </article>
            <hr className='hr' ></hr>

            <TESTFOOT/>
        </div>
        
        </>
        )
    }