import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useState } from "react";
import img from "../public/image/1.png"
import img1 from "../public/image/callbg.jpg"
import img2 from "../public/image/call.jpg"
import img3 from "../public/image/3.jpg"
import img4 from "../public/image/w2.jpg"
import Header1 from "../public/header2"
// import styles from '@/styles/globals.css'




// const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    // async function getgun() {
    //     const config = {
    //         headers: { "content-type": "multipart/form-data" },
    //     };
    //     await axios.get("https://www.imgen.site/imgen2/api_male/api.php",config).then((response) => {
    //         var datax = response.data;
    //         if (datax.status == "success") {
    //             console.log(datax)
    //         } else {
    //             alert("fail")
    //             console.log(datax)
    //         }

    //     });
    // }


    //    const [gunlist,setgunlist] = useState([]) ;
    //    const getgun = () =>{
    //     axios.post('https://www.imgen.site/imgen2/api_male/api.php').than ((response)=>{
    //     setgunlist(response.data);    
    //     });
    //    }

    //     axios.post('https://www.imgen.site/imgen2/api_male/api.php', {x: 1, buf: new Buffer(10)}, {
    //       headers: {
    //         'Content-Type': 'multipart/form-data'
    //       }
    //     }).then(({data}) => console.log(data));




    // async function getcategory() {
    //     if ((pageLoaded2) != true) {
    //         const config = {
    //             headers: { "content-type": "multipart/form-data" },
    //         };
    //         await axios.get("https://www.imgen.site/shop/DB/Api.php?FN=GET_CATEGORYS", config)
    //             .then((response) => {
    //                 let datax = response.data;

    //             });
    //     }
    // }
    const [gunlist, setgunlist] = useState();
    const getgunlist = () => {
        axios.get("https://www.imgen.site/imgen2/api_male/api.php").then((response) => {
            setgunlist(response.data.data);
        });
    };
    getgunlist()
    const card = [
        {
            image: img,
            title: '(data.categorys_name)',
            text: "dhjshdjshdjk",
            dow: "download"
        },
        {
            image: img2,
            title: "Card title",
            text: "dhjshdjshdjk",
            dow: "download"
        }
        , {
            image: img,
            title: "Card title",
            text: "dhjshdjshdjk",
            dow: "download"
        }
        , {
            image: img,
            title: "Card title",
            text: "dhjshdjshdjk",
            dow: "download"
        }, {
            image: img,
            title: "Card title",
            text: "dhjshdjshdjk",
            dow: "download"
        }



    ]



    return (
        <>
            <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* head */}

            <Header1 />



            <div className='container'>
                <div className='row row-cols-2 row-cols-lg-5 g-2 g-lg-3'>
                    {gunlist?.map((item, index) => (
                        <div className="col">
                            <div className="card" >
                                <Image width={245} height={200} src={item.path}
                                    className="card-Image-top" alt="..." />
                                <div className="card-body">
                                    <h5 className="card-title">{item.file_name}</h5>
                                    <p className="card-text">{item.uploaded_on}</p>
                                    <a href={item.path} className="btn btn-primary">download</a>
                                </div>
                            </div>
                        </div>

                    ))}

                </div>
            </div>



        </>
    )
}
