// import styles from '@/styles/index.css'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header0 from "../public/image/header"
import TESTFOOT from "./testfoot"
import a from "../public/image/0.jpg"
import b from "../public/image/9.jpg"
import c from "../public/image/99.jpg"
import aa from "../public/image/00.jpg"
import bb from "../public/image/888.jpg"
import k from "../public/image/k1.jpg"
import ak from "../public/image/ka.jpg"
import Link from 'next/link'
import Header1 from "../public/header2";


export default function Protector() {
    return (
        <>
        <Head>
                <title>Call of DUTY®</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header1 />
        <div className='p-0 batta  align-content-center'>
            <article className='card _2jwgMFDkSKSr-foNIF_7f9'>

                <Image className='p-0  img-fluid  _2yWxQtB7xJRsFyvEkRLyW' src={bb} alt="#" />

                <section className='container-xxlg accordion-body cam1 justify-content-center PGIVj9NTYRWLNncBni330 px-4 '>
                    
                        <h3 className='_2rgIsi3tJYjXp_0uWKfrBZ fs-4'>FEBRUARY 23, 2023</h3>
                        <h1 className='fs-1'>SUPPORT VETERANS WITH THE CALL OF DUTY ENDOWMENT (C.O.D.E.) PROTECTOR PACK FOR CALL OF DUTY®: MODERN WARFARE® II AND CALL OF DUTY®: WARZONE™ 2.0 </h1>
                    
                    <div className='nOk1K0s0zezhHodo4OuM3'>
                        <div>
                            <ul>
                                <li className='tag-item fs-4'>
                                    NEWS
                                </li>
                                <li className='tag-item fs-4'>
                                    Mode Recon
                                </li>

                            </ul>
                            <br></br>
                            <br></br>
                            <hr className='hr' ></hr>
                            <Image className='imgg' src={k} height={500} width={1200} alt="#" />
                           <p className=' fs-3 '></p>
                           <p className=' fs-3 '>Support U.S. and U.K. military veterans by purchasing the ten-item Call of Duty Endowment Protector Pack for Modern Warfare® II and Warzone 2.0, available now.</p>


                           <p className=' fs-3 '>With the launch of Season 02 of Call of Duty®: Modern Warfare® II and <Link href=''>Call of Duty®: Warzone™ 2.0</Link>, you ll need all the gear you can get your hands on to battle it out across new Multiplayer maps and Ashika Island, a brand-new environment in Warzone 2.0. So why not gear up and support a good cause while doing so?</p>
                           <p className=' fs-3 '>Support military veterans by purchasing the Call of Duty Endowment <Link href=''>(C.O.D.E.) Protector Pack</Link> for use in Modern Warfare II, and purchasable for the first time, in Warzone 2.0. By buying the Protector Pack, you will be directly contributing to the Endowment s mission to place unemployed and underemployed veterans in the U.S. and U.K. into high-quality jobs.</p>
                           <h5 className=' fs-1 '>The C.O.D.E. Protector Pack</h5>
                            <Image className='imgg' src={a} height={500} width={1200} alt="#" />
                           <p className=' fs-3 '></p>
                           <h5 className=' fs-1 '>Purchase the Protector Pack to immediately unlock the following in-game items:

                            </h5>
                            <ul>
                                <li className='lli fs-4'>“The Protector” Operator Skin for Hutch</li>
                                <li className='lli fs-4'>“The Protector s Companion” Rifle Blueprint</li>
                                <li className='lli fs-4'>“Duty Calls” Sniper Rifle Blueprint
                                </li>
                                <li className='lli fs-4'>“Frontline Stripes” Vehicle Skin
                                </li>
                                <li className='lli fs-4'>“Ready for Anything” Animated Calli fs-4ng Card
                                </li>
                                <li className='lli fs-4'>“Tagged” Weapon Charm
                                </li>
                                <li className='lli fs-4'>“Seeing Double” Static Animated Emblem
                                </li>
                                <li className='lli fs-4'>1 Hour Double XP Token
                                </li>
                                <li className='lli fs-4'>1 Hour Double Weapon XP Token
                                </li>
                            </ul>
                            <div className='videooo justify-content-center'>
                                <iframe className='videooo justify-content-center' width="850" height="500" src="https://www.youtube.com/embed/R3ePqy9K1Zc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                            </div>

                           <h5 className=' fs-1 '>Meet Hutch, the Protector Pack s Featured Operator</h5>
                            <Image className='imgg' src={b} height={500} width={1200} alt="#" />
                           <p className=' fs-3 '>Hutch has always been good at two things — football and video games. For obvious reasons (hes built like a house and moves like a panther), he was encouraged to pursue the former. The eldest of three boys, Hutch was a protective brother and a natural leader with a tendency to push limits — in life, in the classroom, and on the field. Hutch never gave up his love for gaming and his knack for building computers, his mind, and his body for peak performance. His hard work and dedication paid off when he was rewarded with a scholarship to play college ball and pursue a major in computer science, artificial intelli fs-4gence, and data engineering.</p>
                           <p className=' fs-3 '>While in school, Hutch saw the rising conflict between Russia and Urzikstan and the continued involvement of Western military forces in the embattled region. When the news of the raid by U.S. Marine Corps “Demon Dogs” on Ramaza Hospital successfully captured Al Qatala s leader, known as the “Wolf,” Hutch felt a calli fs-4ng to serve his country and chose to enlist in the Marines.</p>
                           <p className=' fs-3 '>After 4 years of active duty, Hutch elected to complete the rest of his service commitment as a reservist. Always one to have a plan, he called for reinforcement from the Call of Duty Endowment to assist with his military transition. While his time on active duty came to a close, Hutch s new career was just beginning thanks to the Endowment s job placement services, which matched his passion for computers with a competitive career in cybersecurity.</p>
                           <p className=' fs-3 '>A physical beast, Hutch s size, strength, and athleticism made him a standout in the Corps, but his love of computers and technology uniquely qualified him to combine his hardened body and sharp mind, pursuing a path as a Marine network and data specialist. His role exposed him to many facets of securing digital data, configuring cyber services, and advising new developments in digital encryption and cyber capabilities.</p>
                           <h5 className=' fs-1 '>More About the Call of Duty Endowment</h5>
                            <Image className='imgg' src={c} height={500} width={1200} alt="#" />
                           <p className=' fs-3 '></p>

                            <Image className='imgg' src={ak} height={500} width={1200} alt="#" />
                            <div className='videooo justify-content-center'>
                                
                                <iframe className='videooo justify-content-center'  width="850" height="500" src="https://www.youtube.com/embed/Foca7Pa4AF8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                            </div>
                            
                           <p className=' fs-3 '>The Call of Duty Endowment is a nonprofit organization that seeks to help U.S. and U.K. veterans find high-quality careers by supporting groups that prepare them for the job market and by raising awareness of the value vets bring to the workplace. To date, the Endowment has funded the placement of more than 110,000 veterans into good jobs. For more information about the Call of Duty Endowment, please visit <Link href=''>www.callofdutyendowment.org. </Link></p>
                           <p className=' fs-3 '>Season 02 Now Live</p>

                           <p className=' fs-3 '>Season 02 of Modern Warfare II and Warzone 2.0 is now live. In addition to a <Link href=''>new WarzoneTM 2.0 map</Link>, which is featured in Resurgence and DMZ game modes, this update brings Ranked Play to Multiplayer along with four additional maps plus returning modes from the franchise s storied past. Expect plenty of new features across both games, including four new free functional weapons and the return of the modern samurai Daniel “Ronin” Shinoda.</p>

                           <p className=' fs-3 '>Stay frosty.</p>
                           <p className=' fs-3 '>© 2019-2022 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY WARZONE, and MODERN WARFARE are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the property of their respective owners.</p>

                           <p className=' fs-3 '>For more information, please visit<Link href=''> www.callofduty.com</Link> and <Link href=''>www.youtube.com</Link>/callofduty, and follow <Link href=' '>@Activision</Link> and <Link href=''>@CallofDuty</Link> on Twitter, Instagram, and Facebook.</p>


                            <hr className='hr' ></hr>
                            <div>
                                <span className='spann'>
                                    <Link className='spann' href='/'>
                                        <span>Back to Blog Index</span>
                                    </Link>
                                </span>
                            </div>

                        </div>
                    </div>
                </section>



            </article>
            <hr className='hr' ></hr>

            <TESTFOOT />
        </div>
       </>
    )
}


