// import styles from '@/styles/index.css'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header0 from "../public/image/header"
import TESTFOOT from "./testfoot"
import bl from "../public/image/ball.jpg"
import bal from "../public/image/bl.jpg"
import av from "../public/image/at.jpg"
import mn from "../public/image/mnp.jpg"
import Link from 'next/link'
import Header1 from "../public/header2";



export default function RELOADED() {
    return (<>
        <Head>
        <title>Call of DUTY®</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header1 />
        <div className='p-0 batta  align-content-center'>
            <article className='card'>

                <Image className=' p-0  img-fluid _2yWxQtB7xJRsFyvEkRLyW' src={bl} alt="#" />

                <section className=' container-xxlg accordion-body cam1 justify-content-center  PGIVj9NTYRWLNncBni330'>
                    <header>
                        <h3 className='fs-4 text-secondary'>DECEMBER 13, 2022</h3>
                        <h1  className='fs-1'> SEASON 01 RELOADED: WHAT TO KNOW ABOUT CALL OF DUTY®: WARZONE™ CUP, LIVE DECEMBER 14-23</h1>
                    </header>
                    <div className='text-secondary p-1'>
                        <div>
                            <p className=' fs-3 '>During Season 01 Reloaded, Call of Duty®: Warzone™ 2.0 will have a limited-time Call of Duty®: WarzoneTM Cup mode from December 14 at 10 a.m. PT to December 23 at 10 a.m. PT to close out its Modern Warfare® FC event.</p>
                            <p className=' fs-3 '>The marquee free-to-play limited-time mode for Modern Warfare® FC will be launched during Season 01 Reloaded  get the intel you need to reach those #SquadGoals.</p>
                            <ul>
                                <li className='tag-item'>
                                    Mode Recon
                                </li>
                            </ul>
                            <hr className='hr' ></hr>
                            <p className=' fs-3 '>Free for all players, this limited-time mode is a complete change of pace from traditional Call of Duty® modes, as it brings Operators together onto a virtual pitch for some sporting fun. Those who are skilled in vehicular combat will be more than prepared when this mode kicks off, so long as they have a few reliable teammates to help them reach those #SquadGoals. Read on to learn what you need to know about the WarzoneTM Cup.</p>
                            <h5 className=' fs-1 '>Warzone Cup Mode Intel</h5>
                            <Image className='imgg' src={bal} height={500} width={1200} alt="#" />
                            <p className=' fs-3 '>Warzone Cup pits two teams of three Operators against each other at Al Easima Field, a modern sports stadium within the greater <Link href=''>Call of Duty®: Modern Warfare®</Link> II universe.</p>
                            <p className=' fs-3 '>Each Operator will drive an ATV as they attempt to knock a massive ball into the other team s goal within an eight-minute time limit. After each goal, the ball and all Operators are reset to their starting positions to resume play. The first team to reach five goals, or the team that gets the most goals within eight minutes, wins the match.</p>
                            <Image className='imgg' src={av} height={500} width={1200} alt="#" />
                            <p className=' fs-3 '>Unlike other Call of Duty modes, there are no Loadouts or traditional weaponry in this mode. Instead, each ATV is equipped with a pulse ability that sends a powerful burst of energy toward the ball or other ATVs. Combined with simply ramming objects with the ATV, this energy pulse can help redirect the ball toward fellow squadmates or away from your goal.</p>
                            <p className=' fs-3 '>Operators also have one of two ways to disrupt their opponents:</p>
                            <ul>
                                <li className='lli fs-4 '>If an Operator rams into an enemy player at top speed, they destroy that Operator s ATV, temporarily removing them from the pitch and forcing a respawn.</li>
                                <li className='lli fs-4 '> Operators can pick up Shock Sticks around the stadium, which can be thrown at enemy ATVs to temporarily disable their movement.</li>
                            </ul>
                            <p className=' fs-3 '>Winning a game of Warzone Cup not only requires aggressively taking out the enemy team, but also coordinating with squadmates to score goals and prevent the enemy team from gaining possession of the ball. These strategies may involve taking tactics from more traditional versions of this classic game or combining “violence and timing” to render the enemy defenses immobile and out of competition before racking up those #SquadGoals.</p>
                            <h5 className=' fs-1 '>Modern Warfare FC Limited-Time Operator Bundles Still Available</h5>
                            <Image className='imgg' src={mn} height={500} width={1200} alt="#" />
                            <p className=' fs-3 '>All three Modern Warfare FC Limited-Time Bundles — the <Link href=''>Neymar Jr </Link>Operator Bundle (Tracer Pack), Tracer Pack: <Link href=''>Paul Pogba</Link> Operator Bundle, and Tracer Pack: <Link href=''>Messi</Link> Operator Bundle — are still available for purchase within the in-game store. And each one comes with its star Operator along with other items to complete a kit fit for Warzone Cup or elsewhere in Modern Warfare® II or WarzoneTM 2.0:</p>
                            <p className=' fs-3 '>The Neymar Jr Operator Bundle (Tracer Pack) includes the fearless Neymar Jr. Operator, as well as the stealthy “The Feared” Weapon Blueprint and the “Longball” Weapon Blueprint.</p>
                            <p className=' fs-3 '>The Tracer Pack: Paul Pogba Operator Bundle has the French midfielder Paul Pogba as a playable Operator, as well as the “Series A” Weapon Blueprint meant for silent support and the “Counter Attack” Weapon Blueprint for getting high shots on target.</p>
                            <p className=' fs-3 '>Finally, the Tracer Pack: Messi Operator Bundle gives you the legendary Leo Messi as an Operator, along with the sleek “Atomic Flea” Weapon Blueprint and the all-around solid “Blue Thunder” Weapon Blueprint.</p>
                            
                            <div className='videooo justify-content-center'>
                            <iframe className='videooo' width="850" height="500" src="https://www.youtube.com/embed/EwoXZw1RKUA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                            </div>
                            <p className=' fs-3 '>Stay frosty.</p>
                            <p className=' fs-3 '>© 2019-2022 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, CALL OF DUTY WARZONE, and MODERN WARFARE are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the property of their respective owners.</p>
                            
                            <p className=' fs-3 '>For more information, please visit<Link href=''> www.callofduty.com</Link> and <Link href=''>www.youtube.com</Link>/callofduty, and follow <Link href=' '>@Activision</Link> and <Link href=''>@CallofDuty</Link> on Twitter, Instagram, and Facebook.</p>


                            <br></br>
                            <br></br>
                            <hr className='hr' ></hr>

                            <div>
                                <span className='spann'>
                                    <Link className='spann' href='/'>
                                        <span>Back to Blog Index</span>
                                    </Link>
                                </span>
                            </div>

                        </div>
                    </div>
                </section>



            </article>
            <hr className='hr' ></hr>

            <TESTFOOT />
        </div></>
    )
}